include: package:lints/recommended.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    avoid_positional_boolean_parameters: ignore
    avoid_print: ignore

linter:
  rules:
    constant_identifier_names: false
